# build from a node image 
FROM node:14.17.6 as build

WORKDIR /app

COPY package.json .

RUN npm install 

COPY . /app

# multi-stage builds
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

# nginx default port 
EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
